# Generated by Django 5.2.2 on 2025-06-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
