# Generated by Django 5.2.2 on 2025-06-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_for', models.CharField(choices=[('me', 'Me'), ('other', 'Other Person'), ('family', 'Family Member')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'EmergencyRequest',
            },
        ),
    ]
