# Generated by Django 5.2.2 on 2025-06-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('help_for', models.BooleanField(choices=[(True, 'Me'), (False, 'Other Person')], default=True)),
                ('location_info', models.CharField(max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('assigned_to', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'EmergencyRequest',
            },
        ),
    ]
