# Generated by Django 5.2.2 on 2025-06-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyServices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='type',
            field=models.CharField(default=True, max_length=25),
        ),
    ]
