# Generated by Django 5.2.2 on 2025-06-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyServices', '0002_emergencyrequest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='type',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
