# Generated by Django 5.2.2 on 2025-06-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyServices', '0003_alter_emergencyrequest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='assigned_to',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('resolved', 'resolved')], default='pending', max_length=20, null=True),
        ),
    ]
