# Generated by Django 5.2.2 on 2025-06-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyServices', '0004_emergencyrequest_assigned_to_emergencyrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='assigned_to',
            field=models.CharField(default='unassigned', max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('resolved', 'resolved')], default='pending', max_length=20),
        ),
    ]
