# Generated by Django 5.2.2 on 2025-06-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyServices', '0004_alter_emergencyrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='location_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
