# Generated by Django 5.2.2 on 2025-06-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyServices', '0005_alter_emergencyrequest_location_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='assigned_to',
            field=models.CharField(choices=[('ambulance_1', 'Ambulance 1'), ('ambulance_2', 'Ambulance 2'), ('police_1', 'Police 1'), ('police_2', 'Police 2'), ('firefighters_1', 'Fire Fighters 1'), ('firefighters_2', 'Fire Fighters 2')], max_length=50),
        ),
    ]
