# Generated by Django 5.2.2 on 2025-06-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyServices', '0006_alter_emergencyrequest_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='type',
            field=models.CharField(max_length=25),
        ),
    ]
