# Generated by Django 5.2.2 on 2025-06-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyServices', '0006_alter_emergencyrequest_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='assigned_to',
            field=models.CharField(max_length=50),
        ),
    ]
